# Jekyll
markdown: rdiscount
highlighter: "pygments"
permalink: /:title.html

# Conference info
conf:
  name: "Google I/O Extended Belém 2015"
  description: "Versão extendida da famosa conferência anual do Google, agora em Belém."
  date: "28 de maio"
  price: "Entrada gratuita"
  address: "Ceamazon, Ufpa, Belém"
  venue: "-1.466837232,-48.44704006"
  city: "Belém"

# Site info
site:
  url: "http://gdgbelem.com.br"
  favicon: "/img/favicon.ico"
  googleanalytics: ""
  images:
    cover: "/img/banner-iobelem-2015.png"
    facebook: "" #http://braziljs.org/img/fb-share.jpg"

subscribe_text: "Inscreva-se"
subscribe_url: "http://www.eventick.com.br/"

# Active sections on the website
sections:
  about: true
  c4p: false
  location: true
  speakers: false
  schedule: true
  sponsors: true
  partners: true
  contact: false

# The entire schedule
schedule:
  -
    name: "Credenciamento"
    time: "12:00"
  -
    name: "Abertura do evento"
    time: "12:30"
  -
    name: "Transmissão ao vivo do keynote principal do Google I/O"
    time: "13:00"
  -
    name: "Intervalo para coffee-break e networking"
    time: "15:30"
  -
    name: "Shark-bowl sobre os temas apresentados"
    time: "16:10"
  -
    name: "Milton Alcântara"
    photo: "https://pbs.twimg.com/profile_images/460568362712457217/V1DMCrM6.jpeg"
    bio: "Empregado da BB Tecnologia, especialista em Material Design."
    company: "BB Tecnologia e Serviços"
    twitter: "miltonalcantara"
    presentation:
      title: "Introdução ao Material Design"
      description: "O que é o Material Design?  Tudo para você ficar por dentro desta nova tecnologia do Google."
      time: "16:50"
  -
    name: "Larissa Guimarães"
    photo: "https://pbs.twimg.com/profile_images/587422043735457792/jPQJr3Bh.jpg"
    bio: "Empregada da BB Tecnologia, especialista em Android Wear."
    company: "BB Tecnologia e Serviços"
    twitter: "lariguimar"
    presentation:
      title: "Conhecendo o Android Wear"
      description: ""
      time: "17:40"
  -
    name: "Momento dos patrocinadores, sorteio de brindes e encerramento."
    time: "18:10"

# List of Sponsors
sponsors:
  -
    name: "Google Brasil"
    logo: "/img/google.png"
    url: "http://www.google.com.br"
  -
    name: "Inteceleri Solução"
    logo: "/img/inteceleri.png"
    url: "http://www.inteceleri.com.br"
  -
    name: "Editora Novatec"
    logo: "/img/novatec.png"
    url: "http://www.novatec.com.br"
  -
    name: "Jambu Tecnologia"
    logo: "/img/jambutec.png"
    url: "http://www.jambu.com.br"
  -
    name: "BB Tecnologia e Serviços"
    logo: "/img/bbts.png"
    url: "http://www.jambu.com.br"
  -
    name: "Ideias Mobile"
    logo: "/img/ideias.png"
    url: "http://www.ideiasmobile.com.br"
  -
    name: "Android na Rede"
    logo: "/img/android.png"
    url: "http://www.androidnarede.com.br"

# List of Partners
partners:
  -
    name: "BrazilJS"
    logo: "http://f.cl.ly/items/2N3i2W0X2f3c2g2Z2N0f/Untitled-1.png"
    url: "http://braziljs.org"

# About section
about_section:
   title: "Sobre o evento"
   description: 
    - 
      p: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
    - 
      p: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

# Call for papers section
c4p_section:
   title: "Call for papers"
   text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
   c4p_url: "http://call4paperz.com"
   c4p_caption: "Submit"
   c4p_rules_url: "http://call4paperz.com"
   c4p_rules_caption: "Read the rules."

# Contact section
contact_section:
   title: "Fale conosco"
   text: "Contate-nos em caso de qualquer dúvida."
   contacts:
   -
     title: "Email"
     link: "mailto:comunidadetasafo@gmail.com"
   -
     title: "Facebook"
     link: "https://www.facebook.com/GDGBelem"
   email: "comunidadetasafo@gmail.com"
   twitter_url: "http://twitter.com/gdgbelem"
   twitter_username: "@gdgbelem"
   show_form: false
   form:
    action: "contato.php"
    name: "Qual seu nome?"
    email: "Qual seu e-mail?"
    message: "Deixe-nos uma mensagem"
    send_button: "Enviar"

# Location section
location_section:
   title: "Local"

# Partners section
partners_section:
   title: "Parceiros"
   show_your_logo_here: false

# Schedule section
schedule_section:
   title: "Agenda"
   text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam."
   time: "Horário"
   slot: "Espaço"
   description: "Descrição"

# Speakers section
speakers_section:
   title: "Palestrantes"

# Sponsors section
sponsors_section:
   title: "Patrocinadores"
   show_your_logo_here: false
