# Jekyll
markdown: rdiscount
highlighter: "pygments"
permalink: /:title.html

# Conference info
conf:
  name: "Google I/O Extended Belém 2015"
  description: "Versão extendida da famosa conferência anual do Google, agora em Belém."
  date: "28 de maio"
  price: "Entrada gratuita"
  address: "Parque de Ciência e Tecnologia do Guamá - Av. Perimetral 2651, prédio 01 (Ceamazon), UFPA, Belém, PA"
    coords: "-1.466881,-48.446978"
  venue: "Ceamazon, Ufpa, Belém"
  city: "Belém"

# Site info
site:
  url: "http://gdgbelem.com.br"
  favicon: "/img/favicon.ico"
  googleanalytics: ""
  images:
    cover: "/img/banner-iobelem-2015.png"
    facebook: "" #http://braziljs.org/img/fb-share.jpg"

subscribe_text: "Inscreva-se"
subscribe_url: "http://www.eventick.com.br/"

# Active sections on the website
sections:
  about: true
  c4p: false
  location: true
  speakers: false
  schedule: true
  sponsors: true
  partners: true
  contact: false

# The entire schedule
schedule:
  -
    name: "Credenciamento"
    time: "12:00"
  -
    name: "Abertura do evento"
    time: "12:30"
    description: "Apresentação do GDG Belém."
  -
    name: "Keynote do Google I/O"
    time: "13:00"
    description: "Transmissão ao vivo via streaming da principal palestra-show do Google I/O"
  -
    name: "Intervalo"
    time: "15:30"
    description: "Pausa para coffee-break e networking entre os participantes."
  -
    name: "Shark-bowl"
    time: "16:10"
    description: "Discussões abertas com opiniões e debates sobre assuntos relevantes."
  -
    name: "Milton Alcântara"
    photo: "https://pbs.twimg.com/profile_images/460568362712457217/V1DMCrM6.jpeg"
    bio: "Empregado da BB Tecnologia, especialista em Material Design."
    company: "BB Tecnologia e Serviços"
    twitter: "miltonalcantara"
    presentation:
      title: "Introdução ao Material Design"
      description: "O que é o Material Design?  Tudo para você ficar por dentro desta nova tecnologia do Google."
      time: "16:50"
  -
    name: "Larissa Guimarães"
    photo: "https://pbs.twimg.com/profile_images/587422043735457792/jPQJr3Bh.jpg"
    bio: "Empregada da BB Tecnologia, especialista em Android Wear."
    company: "BB Tecnologia e Serviços"
    twitter: "lariguimar"
    presentation:
      title: "Conhecendo o Android Wear"
      description: "Android Wear.  Conheça o básico da programação para dispositívos “vestíveis”."
      time: "17:40"
  -
    name: "Encerramento"
    description: "Momento dos patrocinadores e sorteio de brindes."
    time: "18:10"

# List of Sponsors
sponsors:
  -
    name: "Google Brasil"
    logo: "/img/google.png"
    url: "http://www.google.com.br"
  -
    name: "Inteceleri Solução"
    logo: "/img/inteceleri.png"
    url: "http://www.inteceleri.com.br"
  -
    name: "Editora Novatec"
    logo: "/img/novatec.png"
    url: "http://www.novatec.com.br"
  -
    name: "Jambu Tecnologia"
    logo: "/img/jambutec.png"
    url: "http://www.jambu.com.br"
  -
    name: "BB Tecnologia e Serviços"
    logo: "/img/bbts.png"
    url: "http://www.jambu.com.br"
  -
    name: "Ideias Mobile"
    logo: "/img/ideias.png"
    url: "http://www.ideiasmobile.com.br"
  -
    name: "Android na Rede"
    logo: "/img/android.png"
    url: "http://www.androidnarede.com.br"

# List of Partners
partners:
  -
    name: "Ceamazon"
    logo: "/img/ceamazon.png"
    url: "http://www.ceamazon.com.br"
  -
    name: "PCT Guamá"
    logo: "/img/pctguama.png"
    url: "http://pctguama.org.br"
  -
    name: "UFPA"
    logo: "/img/ufpa.png"
    url: "http://www.ufpa.br"
  -
    name: "Altos Eventos"
    logo: "/img/altoseventos.png"
    url: "http://www.facebook.com/AltosEventos"
  -
    name: "Tá Safo!"
    logo: "/img/tasafo.png"
    url: "http://tasafo.wordpress.com"

# About section
about_section:
   title: "Sobre o evento"
   description: 
    - 
      p: "A Google I/O é a famosa convenção técnica anual da Google que acontece na Califórnia EUA e é transmitida para mais de 140 países. Desenvolvedores e empreendedores de base tecnológica do mundo todo se reúnem para acompanhar as transmissões em extensões locais do evento que são combinadas com atividades colaterais de interesse específico, as “Google I/O Extended”."
    - 
      p: "Neste ano a Google I/O Extended Belém será organizada pelo GDG (Google Developers Group) em parceria com várias empresas locais e entusiastas da economia digital. Além da transmissão do keynote oficial diretamente da sede da Google, o evento contará com palestras exclusivas, reunindo empreendedores, investidores e profissionais de TI num ambiente corporativo para proporcionar a troca de experiências, networking, feedback especializado e enriquecimento geral da comunidade empreendedora digital da cidade."

# Call for papers section
c4p_section:
   title: "Call for papers"
   text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
   c4p_url: "http://call4paperz.com"
   c4p_caption: "Submit"
   c4p_rules_url: "http://call4paperz.com"
   c4p_rules_caption: "Read the rules."

# Contact section
contact_section:
   title: "Fale conosco"
   text: "Contate-nos em caso de qualquer dúvida."
   contacts:
   -
     title: "Email"
     link: "mailto:comunidadetasafo@gmail.com"
   -
     title: "Facebook"
     link: "https://www.facebook.com/GDGBelem"
   email: "comunidadetasafo@gmail.com"
   twitter_url: "http://twitter.com/gdgbelem"
   twitter_username: "@gdgbelem"
   show_form: false
   form:
    action: "contato.php"
    name: "Qual seu nome?"
    email: "Qual seu e-mail?"
    message: "Deixe-nos uma mensagem"
    send_button: "Enviar"

# Location section
location_section:
   title: "Local"

# Partners section
partners_section:
   title: "Parceiros"
   show_your_logo_here: false

# Schedule section
schedule_section:
   title: "Agenda"
   text: ""
   time: "Horário"
   slot: "Espaço"
   description: "Descrição"

# Speakers section
speakers_section:
   title: "Palestrantes"

# Sponsors section
sponsors_section:
   title: "Patrocinadores"
   show_your_logo_here: false
